name: tmol
dependencies:
  # Development and test packages
  - python=3.6
  - ipython
  - ipykernel
  - numba
  - seaborn
  - biopython
  - flake8
  - pytest
  - pytest-cov
  - pyrosetta=2017.48.post.dev+119.fordas.devbase.cce4ea9c848

  - pip:
    - yapf
    - pytest-watch
    - pytest-instafail
    - pytest-faulthandler
    - pdbpp
